updated ocrmypdf to handle failures

diff --git a/files/installed_scripts/ocrallpdf b/files/installed_scripts/ocrallpdf
--- a/files/installed_scripts/ocrallpdf
+++ b/files/installed_scripts/ocrallpdf
@@ -11,6 +11,8 @@ if [ ! -d "$1" ]; then
     exit 1
 fi
 
+failures=()
+
 # Loop through each PDF file
 for file in "$1"/*.pdf; do
     filename=$(basename -- "$file" .pdf)
@@ -23,7 +25,22 @@ for file in "$1"/*.pdf; do
     # pdftk "$dir/output_no_tags.pdf" output "$dir/$filename.pdf" compress
     # rm "$dir/output_no_tags.pdf"
 
+    if [[ "$filename" == "OCR"* ]]; then
+        echo "\"$dir/$filename.pdf\" has OCR in its name. Skipping"
+        continue
+    fi
+
     # OCR the PDF
     echo "ocrmypdf --skip-text \"$dir/$filename.pdf\" \"$dir/OCR_$filename.pdf\""
     ocrmypdf --skip-text "$dir/$filename.pdf" "$dir/OCR_$filename.pdf"
+
+    if ! [ -f "$dir/OCR_$filename.pdf" ]; then
+        failures+=("$dir/OCR_$filename.pdf")
+        cp "$dir/$filename.pdf" "$dir/OCR_$filename.pdf"
+    fi
+done
+
+echo "Failures:"
+for element in "${failures[@]}"; do
+    echo "$element"
 done
